steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_API_URL'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'
substitutions:
  _IMAGE_NAME: crux-dev-web
  _API_URL: https://crux-dev-api-273165967255.us-central1.run.app
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
